### ISSUE TITLE
installation impossible sans fournir de clé ssh

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/ssh_chroot_dir_ynh#8]
C'est marqué comme optionnel, mais on ne peut pas la laisser vide, même si le mot de passe est fourni.
Edit : via l'interface admin, en ligne de commande ça marche.

**Comment by maniackcrudelis** [comment]
Looks like it's a bug from the admin panel, unless you have an error during the install process.
But, if the field can't be left empty, then that's an issue from the admin panel. In that case, you should open an issue on the bug tracker of YunoHost directly.
https://github.com/YunoHost/issues/issues

**Comment by tomdereub** [comment]
Now I have the contrary, I can't install it without password, even in command line...

**Comment by maniackcrudelis** [comment]
Is it a error message about the size of your password ? With a disclaimer about the password not being strong enough ?

**Comment by tomdereub** [comment]
Yes it is, if you don't give a password it says "password must be minimum 8 characters".

**Comment by maniackcrudelis** [comment]
I opened an issue about it months ago
https://github.com/YunoHost/issues/issues/1261

Meanwhile, you can use one of those 2 commands (don't know which one concerns apps)
```
sudo yunohost settings set security.password.admin.strength -v -1
sudo yunohost settings set security.password.user.strength -v -1
```

`sudo yunohost settings get security.password.admin.strength` will gives you the value it contains if you want to set it back.
The 2 previous will get rid of the limitation about passwords in YunoHost globally.

**Comment by tomdereub** [comment]
Ok, but if you do that, it will give an empty password, won't it ? My idea is to make it impossible to connect with password, not to give an empty password that would give an easy access.

**Comment by maniackcrudelis** [comment]
No the password is optional, if you don't give one the app will use the ssh key only.
The problem here is that YunoHost won't allow an empty password, even if it's optional into the manifest.
The fix done by Aleks will probably fix that.
I need to find some will to try it...

**Comment by tomdereub** [comment]
Ok, this solution worked. I set the user to -1 during installation, then 1 again, thanks !
